DROP TABLE IF EXISTS ObjetoBD;
DROP TABLE IF EXISTS Usuario;

CREATE TABLE ObjetoBD(
    id INT PRIMARY KEY,
    creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultMod TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    estado ENUM("ACTIVO","INACTIVO") DEFAULT "ACTIVO",
    tipo VARCHAR(50)
);

CREATE TABLE Usuario(
    id INT PRIMARY KEY,
    usuario VARCHAR(50) UNIQUE,
    contra VARCHAR(50),
    FOREIGN KEY(id) REFERENCES ObjetoBD(id) ON DELETE CASCADE
);
