DROP TABLE IF EXISTS Usuario;
DROP TABLE IF EXISTS ObjetoBD;

CREATE TABLE ObjetoBD(
    id INT AUTO_INCREMENT,
    creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultMod TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    estado ENUM("ACTIVO","INACTIVO") DEFAULT "ACTIVO",
    tipo VARCHAR(50),
    PRIMARY KEY(id)
);
--Contra larga xq va encriptada
CREATE TABLE Usuario(
    id INT PRIMARY KEY,
    usuario VARCHAR(50) UNIQUE,
    contra VARCHAR(500),
    FOREIGN KEY(id) REFERENCES ObjetoBD(id) ON DELETE CASCADE
);
